name: coinbase
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #state-management:
  get: ^4.3.8

  #network:
  http: ^0.13.4
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  # Assets
  assets:
    - assets/images/
    - assets/logos/

  # Fonts
  fonts:
    - family: custom-icons
      fonts:
        - asset: assets/fonts/custom-icons.ttf

    - family: sofia-pro
      fonts:
        - asset: assets/fonts/sofia-pro-bold.ttf
          weight: 700
        - asset: assets/fonts/sofia-pro-bold-italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/sofia-pro-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/sofia-pro-semi-bold-italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/sofia-pro-medium.ttf
          weight: 500
        - asset: assets/fonts/sofia-pro-medium-italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/sofia-pro-regular.ttf
          weight: 400
        - asset: assets/fonts/sofia-pro-regular-italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/sofia-pro-light.ttf
          weight: 300
        - asset: assets/fonts/sofia-pro-light-italic.ttf
          weight: 300
          style: italic